version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      XDEBUG_MODE: "off"
    volumes: ["workspace:/workspace"]
  db:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports: [3307:3306]
    volumes: [mysql-persistence:/var/lib/mysql]
volumes:
  workspace:
  mysql-persistence:
